Docksal configuration improvements.

diff --git a/.docksal/commands/init b/.docksal/commands/init
--- a/.docksal/commands/init
+++ b/.docksal/commands/init
@@ -1,52 +1,52 @@
 #!/usr/bin/env bash
 
-#-------------------------- Settings --------------------------------
+#!/usr/bin/env bash
 
-# PROJECT_ROOT is passed from fin.
-# The following variables are configured in the '.env' file: DOCROOT, VIRTUAL_HOST.
+## Initialize stack and site (full reset)
+##
+## Usage: fin init
 
-SITE_DIRECTORY="default"
-DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
-SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
+# Abort if anything fails
+set -e
 
-#-------------------------- END: Settings --------------------------------
+#-------------------------- Helper functions --------------------------------
 
-# Set docksal-local.env
-cp $PROJECT_ROOT/.docksal/example.docksal-local.env $PROJECT_ROOT/.docksal/docksal-local.env
-# Start containers
-fin up
-# Install
-fin exec composer install
-# Set local config files
-cp $SITEDIR_PATH/default.settings.php $SITEDIR_PATH/settings.php
-cp $SITEDIR_PATH/default.settings.local.php $SITEDIR_PATH/settings.local.php
-cp $SITEDIR_PATH/default.services.local.yml $SITEDIR_PATH/services.local.yml
-# Set extra config
-echo "
+# Console colors
+red='\033[0;31m'
+green='\033[0;32m'
+green_bg='\033[42m'
+yellow='\033[1;33m'
+NC='\033[0m'
 
- if (file_exists(\$app_root . '/' . \$site_path . '/settings.local.php')) {
-   include \$app_root . '/' . \$site_path . '/settings.local.php';
- }
-" >> $SITEDIR_PATH/settings.php
-echo "
-\$databases['default']['default'] = array (
-  'database' => 'default',
-  'username' => 'user',
-  'password' => 'user',
-  'prefix' => '',
-  'host' => '$(fin vm ip)',
-  'port' => '33062',
-  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
-  'driver' => 'mysql',
-);
-" >> $SITEDIR_PATH/settings.local.php
+echo-red () { echo -e "${red}$1${NC}"; }
+echo-green () { echo -e "${green}$1${NC}"; }
+echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
+echo-yellow () { echo -e "${yellow}$1${NC}"; }
+
+#-------------------------- Execution --------------------------------
+# Stack initialization
+echo -e "${green_bg} Step 1 ${NC}${green} Initializing stack...${NC}"
+if [[ ${DOCKER_RUNNING} == "true" ]]; then
+	fin reset -f
+else
+	fin up
+fi
+echo "Waiting 10s for MySQL to initialize...";
+sleep 10
+
+# Site initialization
+echo -e "${green_bg} Step 2 ${NC}${green} Initializing site...${NC}"
+
+# This runs inside cli using http://docs.docksal.io/en/v1.4.0/fin/custom-commands/#executing-commands-inside-cli
+fin init-site
+
+echo -en "${green_bg} ALMOST DONE! ${NC} "
+echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."
+
 # Set hosts
-fin hosts remove $VIRTUAL_HOST
-fin hosts add $VIRTUAL_HOST
-# Install site
-cd $DOCROOT
-fin drush site-install sitefarm_subprofile -y --site-name="SiteFarm Distro"
-# Get login link
-fin drush uli --uri="http://$VIRTUAL_HOST"
-# Set permissions
-sudo chmod 755 $SITEDIR_PATH
+fin hosts remove ${VIRTUAL_HOST}
+fin hosts add ${VIRTUAL_HOST}
+
+echo -en "${green_bg} DONE! ${NC} "
+fin drush uli
+#-------------------------- END: Execution --------------------------------
